Repository AreaLayer/FireBolt, pull requests merged in 2023-07, with the labels that each got.

#39 Add Homepage
  app/ui/home.ts
Labels: Feature

#40 Add transactions
  app/coinjoin/transactions.js
Labels: Feature

#41 Rename seed-lightning.js to seed_lightning.js
  app/data/seed_lightning.js
Labels: Feature

#45 Add Coinswap with testnet
  app/coinjoin/coinswap.js
Labels: documentation, Feature

#44 Update id.js
  app/tbd/id.js
Labels: bug

#47 Initial integration with CoinSelect
  app/bitcoin/select.js
Labels: Feature

#42 Remove section "Product"
  README.md
Labels: Feature

#53 Delete coinjoin.js
  app/bitcoin/coinjoin.js
Labels: documentation, enhancement

#54 Update algorithm.js with Testnet and Mempool
  app/coinjoin/algorithm.js
Labels: documentation, enhancement, Feature

#48 Create KotlinJavascript.xml and remove 'Idea' paste
  .idea/.gitignore
  android/idea/.gitignore
  android/idea/FireBolt.iml
  android/idea/libraries/KotlinJavascript.xml
  android/idea/misc.xml
  android/idea/module.xml
  android/idea/vcs.xml
Labels: documentation, Feature

#51 Update UI
  app/ui/index.js
  app/ui/script.js
  app/ui/style.js
  app/ui/tab.ts
Labels: Feature

#50 Update .gitignore
  .gitignore
Labels: Feature

#57 Update README.md
  README.md
Labels: documentation

#58 Update Coinswap on Roadmap
  README.md
Labels: documentation

#66 Update SECURITY.md
  SECURITY.md
Labels: documentation

#69 Add .npm
  .npm
Labels: documentation, enhancement, Feature

#70 Update npm-publish.yml
  .github/workflows/npm-publish.yml
Labels: documentation, duplicate

#49 Adde .gitignore for "Swift"
  ios/.gitignore
Labels: Feature

#55 Add Mempool API
  app/bitcoin/mempool.js
Labels: documentation, enhancement, Feature

#68 Update index.js
  app/ui/index.js
Labels: enhancement, Feature

#63 Add contact_list.ts for UI
  app/ui/contact_list.ts
Labels: enhancement, Feature

#61 Update README.md
  README.md
Labels: documentation

#67 Add Assets and Icons for UI
  app/ui/assets/contacts.png
  app/ui/assets/mnemonic.png
  app/ui/assets/qr-code.png
  app/ui/assets/safe.png
  app/ui/assets/scan.png
  app/ui/assets/search.png
  app/ui/assets/share.png
  app/ui/assets/test
  app/ui/assets/unmixed.png
  app/ui/assets/visible.png
  app/ui/assets/wallet.png
Labels: documentation, enhancement, Feature

#65 Rename builder.kts to builder.kt
  android/app/src/main/klotin/com/example/bit_nostr_hypercore_wallet/builder.kt
Labels: bug, documentation, enhancement, Feature

#30 Add PayJoin
  app/payjoin/core.js
Labels: Feature

#72 Update tsconfig.json
  jsconfig.json
  tsconfig.json
Labels: enhancement, Feature

#79 Update jsconfig.json
  jsconfig.json
Labels: bug, documentation, good first issue

#56 Update send_receive.js with Taproot
  app/bitcoin/send_receive.js
Labels: documentation, enhancement, Feature

#62 Update transactions.js
  app/coinjoin/transactions.js
Labels: documentation, Feature

#76 Add 'Server'
  app/server/bitcoin.js
  app/server/hypercore.js
  app/server/lightning.js
  app/server/tbd.js
Labels: documentation, enhancement, Feature

#78 Add Multisig
  app/bitcoin/keys.js
Labels: documentation, enhancement, Feature

#77 Remove old code and add new code with Coinjoin and Payjoin integration
  app/bitcoin/miniscript.js
Labels: documentation, enhancement, help wanted, Feature

#75 Add DIDs and NWD Node
  app/tbd/id.js
  app/tbd/node.js
Labels: enhancement

#73 Add LSP
  app/lightning/send_receive.js
Labels: documentation, enhancement, Feature

#71 Update package.json
  .npmc
  package-lock.json
  package.json
Labels: documentation, enhancement

#64 Add Contact list with support ID and Npub
  app/pages/contact_list.js
Labels: documentation, enhancement

#74 Update Roadmap
  README.md
Labels: documentation

#59 Update SECURITY.md
  SECURITY.md
Labels: documentation

#80 Add WIP
  README.md
Labels: documentation

#92 Update id.js
  app/tbd/id.js
Labels: bug, enhancement

#93 Update id.js
  app/tbd/id.js
Labels: enhancement, Feature

#94 Fixed path for Segwit and Taproot
  app/data/seed.js
Labels: documentation

#81 Update build.gradle
  android/build.gradle
Labels: enhancement, Feature

#89 Add Sender and Receiver
  app/payjoin/receiver.js
  app/payjoin/sender.js
Labels: enhancement, Feature

#82 Update package-lock.json
  package-lock.json
Labels: enhancement

#95 Add Android functions on Javascript
  android/app/src/main/klotin/android.js
  android/idea/WebView.xml
Labels: documentation, enhancement, Feature

#91 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement, Feature

#96 Add LDK Binding in Typescript into Javascript
  app/lightning/ldk.js
Labels: documentation, duplicate, enhancement, Feature

#90 Add Node.js status
  README.md
Labels: documentation

#84 Create app.json
  app.json
Labels: enhancement, Feature

#86 Create react-native.config
  react-native.config
Labels: enhancement, Feature

#85 Create index.js
  index.js
Labels: enhancement, Feature

#88 Create babel.config.js
  babel.config.js
Labels: enhancement, Feature

#87 Create .prettierrc.js
  .prettierrc.js
Labels: enhancement

#98 Remove "Coinjoin Demo"
  README.md
Labels: documentation

#107 Update README.md
  README.md
Labels: documentation, enhancement, Feature

#97 Update app.json
  app.json
Labels: documentation, enhancement, Feature

#99 Update app.js
  app.js
Labels: enhancement, Feature

#101 Add compenents for App.js
  app.js
Labels: documentation, enhancement

#106 Add Sats Standard
  app/data/sats.js
Labels: enhancement, Feature
