Repository AreaLayer/FireBolt, pull requests merged in 2023-11, with the labels that each got.

#187 Update manifest.json
  pwa/manifest.json
Labels: documentation, Epic

#178 Add Taproot Channels
  app/lightning/send_receive.js
Labels: documentation, enhancement, Feature, c-priority, lightning network

#190 Update page.html
  pwa/public/page.html
Labels: documentation, enhancement, Feature, Epic

#209 Session for P2P apps
  app/pages/buy_bitcoin.html
Labels: enhancement, Feature, Epic, c-priority, bitcoin, back-end

#221 Remove Apache License
  LICENSE-APACHE
Labels: documentation

#184 Add new version around LDK
  package-lock.json
Labels: documentation, enhancement, Feature, c-priority, bitcoin, lightning network
