Repository AreaLayer/FireBolt, pull requests merged in 2023-08, with the labels that each got.

#105 Add API for Sats and BTC price
  app/data/api.js
Labels: enhancement, Feature

#100 Create appRegistry.js
  android/SomeTaksName.js
  android/appRegistry.js
  android/idea/FireBolt.iml
Labels: enhancement, Feature

#102 Update app.json
  app.json
Labels: documentation, enhancement, Feature

#108 Create AboutAssets.txt
  android/idea/AboutAssets.txt
Labels: documentation, enhancement, Feature

#109 Create AssemblyInfo.js
  android/idea/AssemblyInfo.js
Labels: documentation, enhancement, Feature

#111 Add Balance for Sats, backend timechain, etc
  app.js
Labels: enhancement, Feature

#112 Add PWA
  README.md
Labels: documentation

#113 Add PWA Folder
  pwa/img/index.html
Labels: documentation, enhancement, Feature

#118 Add PWA
  README.md
Labels: documentation, enhancement, Feature

#127 Update README.md
  README.md
Labels: documentation

#114 Add Structure for PWA
  pwa/img/style.css
  pwa/img/sw.js
Labels: enhancement, Feature

#116 Update .gitignore
  ios/.gitignore
Labels: documentation, enhancement, Feature

#115 Update algorithm.js
  app/coinjoin/algorithm.js
Labels: documentation, enhancement, Feature

#120 Remove Status from Node.js
  README.md
Labels: documentation, enhancement, Feature

#117 Create manifest.json
  manifest.json
Labels: documentation, enhancement, Feature

#119 Add Hypercore Folder
  app/hypercore/hypercore.js
Labels: documentation, enhancement, Feature

#123 Update package-lock.json
  package-lock.json
Labels: documentation

#122 Update package.json
  package.json
Labels: documentation

#142 Add Payjoin over Nostr into Roadmap
  README.md
Labels: documentation, enhancement

#124 Add 'Lightning Vortex' into Roadmap for help on Coinjoin
  README.md
Labels: documentation, enhancement, Feature

#121 Update SECURITY.md
  SECURITY.md
Labels: documentation

#143 Add Cargo for Payjoin and be compatible with wallet
  Cargo.toml
Labels: documentation, enhancement, Feature

#146 Add Taproot Channels on Roadmap
  README.md
Labels: documentation, enhancement, Feature

#125 Add vortex.js
  app/coinjoin/vortex.js
Labels: documentation, enhancement, Feature

#141 Add Beta App platforms
  README.md
Labels: documentation, enhancement

#147 Update .gitignore
  .gitignore
Labels: documentation, enhancement, Feature
