Repository AreaLayer/FireBolt, pull requests merged in 2023-09, with the labels that each got.

#148 Update manifest.json
  manifest.json
Labels: documentation, enhancement, Feature

#132 Add LND Server
  app/server/lightning.js
Labels: documentation, enhancement, Feature

#137 Add Home Page
  app/ui/home.js
  app/ui/home.ts
Labels: documentation, enhancement, Feature

#139 Add Components
  components/dataStorage.js
  components/index.js
  components/localStorage.js
Labels: documentation, enhancement, Feature

#140 Add Constants
  constants/index.js
  constants/theme.js
Labels: documentation, enhancement, Feature

#133 Add Bitcoin Server
  app/server/bitcoin.js
Labels: documentation, enhancement, Feature

#134 Add Hypercore Server
  app/server/hypercore.js
Labels: documentation, enhancement, Feature

#135 Add Nostr Server
  app/server/nostr.js
Labels: documentation, enhancement, Feature

#138 Add Index data
  index.js
Labels: documentation, enhancement, Feature

#136 Add Web5 Server
  app/server/tbd.js
Labels: documentation, enhancement, Feature

#149 Delete .github/workflows/jekyll-gh-pages.yml
  .github/workflows/jekyll-gh-pages.yml
Labels: documentation, enhancement

#128 Add Final configuration for CoinjoinXT with Taproot
  app/coinjoin/base.js
  app/coinjoin/command.js
  app/coinjoin/config.js
  app/coinjoin/receiver.js
  app/coinjoin/sender.js
  app/coinjoin/wallet_tool.js
Labels: documentation, enhancement, Feature

#144 Integration with BOLT12 from LDK TS
  app/lightning/ldk.js
Labels: documentation, enhancement, Feature

#131 Add Payjoin over Nostr
  app/payjoin/nostr/receiver.js
  app/payjoin/nostr/sender.js
Labels: documentation, enhancement, Feature

#150 Update README.md
  README.md
  SECURITY.md
  package-lock.json
  package.json
Labels: documentation

#151 Update receiver.js
  app/payjoin/nostr/receiver.js
Labels: enhancement, Feature

#154 Update Roadmap
  README.md
Labels: documentation

#167 Update README.md
  README.md
Labels: documentation, enhancement, Feature

#155 Update app.json
  app.json
Labels: documentation, enhancement, Feature

#159 Update dataStorage.js
  components/dataStorage.js
Labels: documentation, enhancement, Feature

#170 Update .gitignore
  .gitignore
Labels: documentation, enhancement, Feature

#157 Update react-native.config.js
  react-native.config.js
Labels: documentation, enhancement, Feature

#110 Add Steps for run app
  README.md
Labels: documentation, enhancement, Feature

#156 Update jsconfig.json
  jsconfig.json
Labels: documentation, enhancement, Feature

#165 Add Rust module
  app/rust/bitcoind.rs
  app/rust/error.rs
  app/rust/lib.rs
  app/rust/receive.rs
  app/rust/send.rs
Labels: documentation, enhancement, Feature

#173 Add iOs modules for App
  ios/app/appdelegate.swift
  ios/app/scenedelegate.swift
  ios/app/viecontroller.swift
  ios/info.plist
  ios/task.swift
  ios/ui/main.storyboard.swift
Labels: documentation, enhancement, Feature

#172 Add Android modules for App
  android/app/src/main/klotin/com/example/bit_nostr_hypercore_wallet/MainActivity.kt
  android/app/src/main/klotin/com/example/bit_nostr_hypercore_wallet/build.gradle.kt
  android/app/src/main/klotin/com/example/res/value/string.xml
Labels: documentation, enhancement, Feature

#169 Update SECURITY.md
  SECURITY.md
Labels: documentation, enhancement, Feature

#158 Update sw.js
  pwa/img/sw.js
Labels: documentation, enhancement, Feature

#162 Create ui.swift
  ios/ui.swift
Labels: documentation, enhancement, Feature

#161 Update index.js
  components/index.js
Labels: documentation, enhancement, Feature

#164 Update theme.js
  constants/theme.js
Labels: documentation, enhancement, Feature

#163 Update index.js
  constants/index.js
Labels: documentation, enhancement, Feature
