Repository AreaLayer/FireBolt, pull requests merged in 2023-06, with the labels that each got.

#17 Relay on Nostr update and LDK integration
  app/lightning/ldk.js
  app/pages/relay.js
Labels: Feature

#16 Algorithm for CoinJoin
  app/coinjoin/algorithm.js
Labels: Feature

#18 Initial integration with LDK-Node-Js
  README.md
Labels: documentation, Feature

#24 Add BIP-39 for Nostr client
  app/nostr/client.js
Labels: Feature

#20 Update algorithm.js
  app/coinjoin/algorithm.js
Labels: Feature

#23 Update README and add Contact list
  README.md
  app/pages/contact_list.js
Labels: documentation

#21 Update client.js
  app/nostr/client.js
Labels: Feature

#29 Update README.md
  README.md
Labels: documentation

#26 Create backup.js
  app/data/backup.js
Labels: Feature

#27 Create sign_nostr.js
  app/nostr/sign_nostr.js
Labels: Feature

#28 Update hyperdrive.js
  app/hypercore/hyperdrive.js
Labels: Feature

#32 Update miniscript.js
  app/bitcoin/miniscript.js
Labels: Feature

#34 Delete payjoin_sender.rs
  app/bitcoin/payjoin_sender.rs
Labels: Feature

#37 Update Coinjoin with new PubKey for avoid privacy issues
  app/coinjoin/algorithm.js
Labels: Feature

#35 Remove "No shitcoins or stablecoins" to "Bitcoin-only" and add Lightning Icon
  README.md
Labels: documentation, Feature

#36 UI
  app/ui/tab.ts
Labels: Feature

#33 Create LICENSE-APACHE
  LICENSE-APACHE
Labels: documentation

#38 Add Coinjoin Demo
  README.md
Labels: documentation, Feature
