Repository AreaLayer/FireBolt, pull requests merged in 2023-10, with the labels that each got.

#176 Update README.md
  README.md
Labels: documentation, enhancement, Feature

#174 Rename ldk.js to ldk.jsx
  app/lightning/ldk.jsx
Labels: enhancement, Feature

#166 Upgrade LN Vortex after initial integration
  app/coinjoin/vortex.js
Labels: documentation, enhancement, Feature

#179 Upgrade Taproot Channels
  README.md
Labels: documentation, enhancement, Feature

#177 Update app.json
  app.json
Labels: documentation, enhancement, Feature

#181 Add Miniscript Lib
  app/bitcoin/miniscript.js
Labels: documentation, enhancement, help wanted, Feature, Epic

#180 Add service-worker.jsx for PWA app
  pwa/manifest.json
  pwa/service/main.jsx
  pwa/service/service-worker.jsx
Labels: enhancement, help wanted, Feature

#171 Add Doc about wallet and run app with Dev mode
  doc/run.md
Labels: documentation, enhancement, Feature

#185 Update package-lock.json
  package-lock.json
  package.json
Labels: documentation, enhancement, Feature, Epic

#182 Update main.storyboard.swift
  ios/ui/main.storyboard.swift
Labels: documentation, enhancement, Feature, Epic

#189 Update .gitignore
  .gitignore
Labels: documentation, enhancement, Epic

#186 Add user doc
  doc/run.md
Labels: documentation, enhancement, Feature, Epic
